# General
test_mode: False
debug: True
run_num: 0
explicit_run_enumeration: False
machine: "local"
device: "cuda"
workdir: "/mnt/d/Aptamer RL/ActiveLearningPipeline/Runs"
# Seeds
seeds:
  sampler: 0
  model: 0
  dataset: 0
  toy_oracle: 0

al:
  mode: rl_gym_test
  gym_env: LunarLander-v2
  dqn_batch_size: 64
  action_size: 4
  state_length: 8
  target_sync_interval: 50
  episodes: 2000
  gamma: 0.99 # discount factor
  alpha: 0.001 # learning rate
  eps_start: 1 
  eps_end: 0.01
  eps_decay: 0.99
  memory_limit: 50000
  min_memory: 500
  tau: 0.1 # target network soft update hyperparameter